name: End-to-end tests

on:
  push:
    branches:
      - main  # ou qualquer outra branch que você queira que dispare a ação
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente'
        required: true
        default: 'devops'
        type: choice
        options:
          - devops
          - stage

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Definir a URL de acordo com o ambiente escolhido
      - name: Set environment URL
        run: |
          if [ "${{ github.event.inputs.environment }}" == "devops" ]; then
            echo "CYPRESS_BASE_URL=https://www.demoblaze.com" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            echo "CYPRESS_BASE_URL=https://www.demoblaze.com" >> $GITHUB_ENV
          fi

      # Instalar dependências do npm
      - name: Install dependencies
        run: |
          npm install

      name: Install dependencies
        run: |
          npm install

      - name: Run Cypress tests with Docker
        run: |
          docker run -e CYPRESS_baseUrl=$CYPRESS_BASE_URL -v $(pwd):/e2e -w /e2e cypress/included:9.0.0

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
